import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import { StorageManager } from "./storage.js";

const WRITE_TIME = "2030-01-02T03:04:05.000Z";
const STALE_HEADER = "*Last updated: 2024-01-02T03:04:05.000Z*";
const FRESH_HEADER = `*Last updated: ${WRITE_TIME}*`;

async function withMemoryDir(run: (dir: string) => Promise<void>): Promise<void> {
  const dir = await mkdtemp(path.join(os.tmpdir(), "remnic-profile-timestamp-"));
  try {
    await run(dir);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

test("writeProfile refreshes a stale header at the write time", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);
      const staleProfile = [
        "# Behavioral Profile",
        "",
        STALE_HEADER,
        "",
        "- Prefers concise status updates.",
        "",
      ].join("\n");

      await storage.writeProfile(staleProfile);

      assert.equal(
        await storage.readProfile(),
        staleProfile.replace(STALE_HEADER, FRESH_HEADER),
      );
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("writeProfile adds one canonical header when content has none", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);

      await storage.writeProfile("# Behavioral Profile\n\n- Values direct communication.\n");

      assert.equal(
        await storage.readProfile(),
        `# Behavioral Profile\n\n${FRESH_HEADER}\n\n- Values direct communication.\n`,
      );
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("writeProfile preserves CRLF line endings", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);

      await storage.writeProfile("# Behavioral Profile\r\n\r\n- Values direct communication.\r\n");

      assert.equal(
        await storage.readProfile(),
        `# Behavioral Profile\r\n\r\n${FRESH_HEADER}\r\n\r\n- Values direct communication.\r\n`,
      );
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("writeProfile removes duplicate stale headers", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);
      await storage.writeProfile([
        "# Behavioral Profile",
        "",
        STALE_HEADER,
        "",
        "*Last updated: 2023-01-02T03:04:05.000Z*",
        "",
        "- Keeps decisions short.",
        "",
      ].join("\n"));

      const profile = await storage.readProfile();
      assert.deepEqual(profile.match(/^\*Last updated:.*\*$/gm), [FRESH_HEADER]);
      assert.match(profile, /- Keeps decisions short\./);
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("writeProfile replaces a noncanonical metadata header", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);
      const profile = [
        "# Behavioral Profile",
        "",
        "*Last updated: before launch*",
        "",
        "- Keeps decisions short.",
        "",
      ].join("\n");

      await storage.writeProfile(profile);

      assert.equal(
        await storage.readProfile(),
        profile.replace("*Last updated: before launch*", FRESH_HEADER),
      );
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("writeProfile recognizes whitespace-only metadata gaps", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);
      const profile = [
        "# Behavioral Profile",
        " \t",
        STALE_HEADER,
        "",
        "- Keeps decisions short.",
        "",
      ].join("\n");

      await storage.writeProfile(profile);

      assert.equal(await storage.readProfile(), profile.replace(STALE_HEADER, FRESH_HEADER));
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("writeProfile finds a title after a preamble", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);
      const profile = [
        "Generated by the profile importer.",
        "",
        "# Behavioral Profile",
        "",
        STALE_HEADER,
        "",
        "- Keeps decisions short.",
        "",
      ].join("\n");

      await storage.writeProfile(profile);

      assert.equal(await storage.readProfile(), profile.replace(STALE_HEADER, FRESH_HEADER));
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("writeProfile does not treat fenced headings as a profile title", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);
      const profile = ["```shell", "# install dependencies", "```", ""].join("\n");

      await storage.writeProfile(profile);

      assert.equal(await storage.readProfile(), `${FRESH_HEADER}\n\n${profile}`);
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("writeProfile keeps nested fences from exposing code headings", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);
      const profile = [
        "````markdown",
        "```",
        "# install dependencies",
        "```",
        "````",
        "",
      ].join("\n");

      await storage.writeProfile(profile);

      assert.equal(await storage.readProfile(), `${FRESH_HEADER}\n\n${profile}`);
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("writeProfile refreshes an off-slot header outside fenced code", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);
      const profile = [
        "# Behavioral Profile",
        "",
        "- Keeps decisions short.",
        "",
        "## Notes",
        "",
        STALE_HEADER,
        "",
      ].join("\n");

      await storage.writeProfile(profile);

      assert.equal(await storage.readProfile(), profile.replace(STALE_HEADER, FRESH_HEADER));
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("writeProfile keeps fence lines with language text inside code", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);
      const profile = [
        "```markdown",
        "```js",
        "# install dependencies",
        "```",
        "",
      ].join("\n");

      await storage.writeProfile(profile);

      assert.equal(await storage.readProfile(), `${FRESH_HEADER}\n\n${profile}`);
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("writeProfile preserves a leading BOM before the title", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);
      const profile = `\uFEFF# Behavioral Profile\n\n${STALE_HEADER}\n\n- Keeps decisions short.\n`;

      await storage.writeProfile(profile);

      assert.equal(await storage.readProfile(), profile.replace(STALE_HEADER, FRESH_HEADER));
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("writeProfile preserves timestamp-shaped indented code", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);
      const profile = [
        "# Behavioral Profile",
        "",
        "## Notes",
        "",
        "    *Last updated: literal example*",
        "",
      ].join("\n");

      await storage.writeProfile(profile);

      assert.equal(
        await storage.readProfile(),
        profile.replace("\n\n## Notes", `\n\n${FRESH_HEADER}\n\n## Notes`),
      );
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("writeProfile keeps four-space fence-like lines inside code", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);
      const profile = [
        "```markdown",
        "    ```",
        "# install dependencies",
        "```",
        "",
      ].join("\n");

      await storage.writeProfile(profile);

      assert.equal(await storage.readProfile(), `${FRESH_HEADER}\n\n${profile}`);
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("writeProfile keeps leading frontmatter before a header", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);
      const profile = ["---", "source: importer", "---", "", "- Keeps decisions short.", ""].join("\n");

      await storage.writeProfile(profile);

      assert.equal(
        await storage.readProfile(),
        `---\nsource: importer\n---\n\n${FRESH_HEADER}\n\n- Keeps decisions short.\n`,
      );
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("writeProfile preserves code examples that mention Last updated", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);
      const profile = [
        "# Behavioral Profile",
        "",
        "## Notes",
        "",
        "    Last updated: database field",
        "",
        "- Uses markdown code examples.",
        "",
      ].join("\n");

      await storage.writeProfile(profile);

      assert.equal(
        await storage.readProfile(),
        profile.replace("\n\n## Notes", `\n\n${FRESH_HEADER}\n\n## Notes`),
      );
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("appendToProfile preserves timestamp-shaped fenced code", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: Date.parse(WRITE_TIME) });
  try {
    await withMemoryDir(async (dir) => {
      const storage = new StorageManager(dir);
      const profile = [
        "# Behavioral Profile",
        "",
        "## Notes",
        "",
        "```markdown",
        STALE_HEADER,
        "```",
        "",
        "- Uses markdown code examples.",
        "",
      ].join("\n");
      await writeFile(path.join(dir, "profile.md"), profile, "utf8");

      await storage.appendToProfile(["Adds durable details."]);

      assert.equal(
        await storage.readProfile(),
        profile.replace("\n\n## Notes", `\n\n${FRESH_HEADER}\n\n## Notes`).trimEnd() +
          "\n- Adds durable details.\n",
      );
    });
  } finally {
    t.mock.timers.reset();
  }
});

test("readProfile does not rewrite a stale header", async () => {
  await withMemoryDir(async (dir) => {
    const storage = new StorageManager(dir);
    const staleProfile = `# Behavioral Profile\n\n${STALE_HEADER}\n\n- Reads are side-effect free.\n`;
    const profilePath = path.join(dir, "profile.md");
    await writeFile(profilePath, staleProfile, "utf8");

    assert.equal(await storage.readProfile(), staleProfile);
    assert.equal(await readFile(profilePath, "utf8"), staleProfile);
  });
});
