/**
 * Cross-reviewer review-thread deduplication (issue #1994, umbrella #1988).
 *
 * A pure, deterministic module — no model dependency, no GitHub API calls — so
 * it is unit-tested against fixtures harvested from the real #1923/#1852
 * duplicate threads and mirrored inline in `.github/workflows/review-thread-guard.yml`
 * (same convention as `scripts/effective-diff.mjs`; keep the two copies in sync).
 *
 * Design invariant (from the issue): precision beats recall everywhere. A missed
 * duplicate costs one redundant reply; a false merge can silence a real bug.
 * Two threads are duplicates ONLY when they share a file, their anchored line
 * ranges overlap, AND their finding fingerprints are lexically similar at or
 * above the committed threshold. Nothing is ever deleted or hidden — a duplicate
 * inherits its canonical's resolution for the guard's unresolved count, and a
 * one-reply `not-a-duplicate` escape hatch detaches it back into the round set.
 */

/**
 * Shipped configuration. The threshold is justified by the committed fixtures
 * (see tests/review-dedup.test.mjs): every real duplicate pair scores at or
 * above it and every one of the 20 sampled non-duplicate pairs scores below it,
 * for measured precision 1.0 on the fixture set.
 */
export const REVIEW_DEDUP_CONFIG = Object.freeze({
  // Word k-shingle size over content tokens. k=1 (content-word set) is the most
  // robust for reviewer paraphrase of the same finding on the same lines.
  shingleSize: 1,
  // Jaccard similarity at or above this merges (given anchor overlap).
  similarityThreshold: 0.5,
});

// Reviewers whose findings are never deduplicated. CodeQL threads cannot be
// resolved via the API and are already excluded by the guard; keep them whole.
export const NON_DEDUP_AUTHOR_LOGINS = new Set([
  "github-advanced-security",
  "github-advanced-security[bot]",
  "github-code-scanning[bot]",
]);

// A single maintainer/agent reply carrying this token detaches a merged thread
// back into the round set — the load-bearing escape hatch against false merges.
const DETACH_PATTERN = /\bnot-a-duplicate\b/i;

// Markup/boilerplate stripped before fingerprinting so badge shields, feedback
// footers, severity tags, and emphasis never dominate the lexical signal.
const CODE_FENCE_PATTERN = /```[\s\S]*?```/g;
const INLINE_CODE_PATTERN = /`([^`]*)`/g;
const IMAGE_PATTERN = /!\[[^\]]*\]\([^)]*\)/g;
const LINK_PATTERN = /\[([^\]]*)\]\([^)]*\)/g;
const HTML_TAG_PATTERN = /<[^>]+>/g;
const SEVERITY_TAG_PATTERN =
  /\b(?:p[0-4]|sev[0-4]|nit|blocker|critical|major|minor|bug|issue|warning|suggestion)\b\s*[:.)\]-]*/gi;
const FEEDBACK_BOILERPLATE_PATTERN =
  /\b(?:was this (?:report|comment) helpful|give feedback|react with|generated by|powered by)\b[\s\S]*$/i;
const EMOJI_PATTERN = /[\p{Extended_Pictographic}\u{1F1E6}-\u{1F1FF}]/gu;
const NON_WORD_PATTERN = /[^a-z0-9]+/g;

// Common English + markdown-noise stopwords. Removing them keeps the fingerprint
// on the finding's nouns/verbs, not connective tissue.
const STOPWORDS = new Set([
  "a", "an", "and", "are", "as", "at", "be", "been", "but", "by", "can",
  "cannot", "could", "de", "do", "does", "for", "from", "has", "have", "if",
  "in", "into", "is", "it", "its", "may", "no", "not", "of", "on", "or", "so",
  "than", "that", "the", "their", "then", "there", "these", "this", "to",
  "up", "was", "we", "when", "which", "will", "with", "would", "you", "your",
  "should", "shall", "here", "how", "why", "what", "where", "who", "this",
]);

/** Strip markdown/HTML/badges/boilerplate from a comment body. */
export function stripMarkup(body) {
  if (typeof body !== "string") return "";
  return body
    .replace(FEEDBACK_BOILERPLATE_PATTERN, " ")
    .replace(CODE_FENCE_PATTERN, " ")
    .replace(IMAGE_PATTERN, " ")
    .replace(LINK_PATTERN, "$1")
    .replace(INLINE_CODE_PATTERN, "$1")
    .replace(HTML_TAG_PATTERN, " ")
    .replace(EMOJI_PATTERN, " ")
    .toLowerCase()
    .replace(SEVERITY_TAG_PATTERN, " ")
    .replace(/[#*_>`~[\]]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Normalized content tokens: markup stripped, stopwords and 1-char tokens dropped. */
export function contentTokens(body) {
  return stripMarkup(body)
    .split(NON_WORD_PATTERN)
    .filter((token) => token.length >= 2 && !STOPWORDS.has(token));
}

/** Deterministic set of word k-shingles over content tokens. */
export function fingerprint(body, shingleSize = REVIEW_DEDUP_CONFIG.shingleSize) {
  const tokens = contentTokens(body);
  const k = Math.max(1, shingleSize | 0);
  if (k === 1) return new Set(tokens);
  const shingles = new Set();
  for (let i = 0; i + k <= tokens.length; i++) {
    shingles.add(tokens.slice(i, i + k).join(" "));
  }
  // A body with fewer than k tokens still contributes its whole token run so it
  // is never silently un-fingerprintable.
  if (shingles.size === 0 && tokens.length > 0) shingles.add(tokens.join(" "));
  return shingles;
}

/** Jaccard similarity of two finding bodies' fingerprints in [0, 1]. */
export function fingerprintSimilarity(
  bodyA,
  bodyB,
  shingleSize = REVIEW_DEDUP_CONFIG.shingleSize,
) {
  const a = fingerprint(bodyA, shingleSize);
  const b = fingerprint(bodyB, shingleSize);
  if (a.size === 0 || b.size === 0) return 0;
  let intersection = 0;
  for (const shingle of a) {
    if (b.has(shingle)) intersection += 1;
  }
  const union = a.size + b.size - intersection;
  return union === 0 ? 0 : intersection / union;
}

/**
 * Blame-relative anchor for a thread. Reuses the guard's thread identity model
 * (GraphQL thread id + first comment) rather than inventing a second one; the
 * line range comes from the review thread's line fields, tolerating the null
 * lines GitHub reports for outdated threads.
 */
export function threadAnchor(thread) {
  const comment = thread?.comments?.nodes?.[0] ?? thread?.firstComment ?? thread;
  const path = comment?.path ?? thread?.path ?? null;
  const rawEnd = thread?.line ?? comment?.line ?? thread?.originalLine ?? comment?.originalLine;
  const rawStart =
    thread?.startLine ?? comment?.startLine ?? thread?.originalStartLine ?? comment?.originalStartLine ?? rawEnd;
  const start = Number.isInteger(rawStart) ? rawStart : null;
  const end = Number.isInteger(rawEnd) ? rawEnd : null;
  return { path, start, end };
}

/**
 * Same file with intersecting line ranges. Missing ranges never overlap: an
 * unknown range is treated as no-overlap (miss = cheap, false merge = feared).
 */
export function anchorsOverlap(a, b) {
  if (!a?.path || !b?.path || a.path !== b.path) return false;
  if (a.start === null || a.end === null || b.start === null || b.end === null) {
    return false;
  }
  const [aLo, aHi] = a.start <= a.end ? [a.start, a.end] : [a.end, a.start];
  const [bLo, bHi] = b.start <= b.end ? [b.start, b.end] : [b.end, b.start];
  return aLo <= bHi && bLo <= aHi;
}

function firstAuthorLogin(thread) {
  return thread?.comments?.nodes?.[0]?.author?.login ?? thread?.author?.login ?? null;
}

function firstBody(thread) {
  return thread?.comments?.nodes?.[0]?.body ?? thread?.body ?? "";
}

/** True when a maintainer/agent has replied `not-a-duplicate` on the thread. */
export function isDetached(thread) {
  const replies = thread?.comments?.nodes ?? thread?.replies ?? [];
  // The first comment is the finding itself; a detach must be a reply to it.
  return replies.slice(1).some((c) => DETACH_PATTERN.test(c?.body ?? ""));
}

function isNonDedupThread(thread) {
  return NON_DEDUP_AUTHOR_LOGINS.has(firstAuthorLogin(thread) ?? "");
}

function stableSort(threads) {
  return threads
    .map((thread, index) => ({ thread, index }))
    .sort((x, y) => {
      const xt = Date.parse(x.thread?.comments?.nodes?.[0]?.createdAt ?? x.thread?.createdAt ?? "");
      const yt = Date.parse(y.thread?.comments?.nodes?.[0]?.createdAt ?? y.thread?.createdAt ?? "");
      const xn = Number.isFinite(xt) ? xt : 0;
      const yn = Number.isFinite(yt) ? yt : 0;
      if (xn !== yn) return xn - yn;
      return x.index - y.index; // Stable tie-break: original filing order.
    })
    .map((entry) => entry.thread);
}

/**
 * Classify each thread as canonical or a duplicate of an earlier canonical.
 * First-seen (earliest by createdAt, then filing order) is canonical.
 *
 * Returns { records, canonicalIds, duplicateCount } where each record is
 * { id, thread, canonicalId, similarity }. canonicalId === id for canonicals,
 * detached threads, and non-dedup (CodeQL) threads.
 */
export function dedupeThreads(threads, config = REVIEW_DEDUP_CONFIG) {
  const threshold = config?.similarityThreshold ?? REVIEW_DEDUP_CONFIG.similarityThreshold;
  const shingleSize = config?.shingleSize ?? REVIEW_DEDUP_CONFIG.shingleSize;
  const ordered = stableSort(Array.isArray(threads) ? threads : []);
  const canonicals = [];
  const records = [];

  for (const thread of ordered) {
    const id = thread?.id ?? null;
    const anchor = threadAnchor(thread);
    const body = firstBody(thread);

    if (isNonDedupThread(thread) || isDetached(thread)) {
      const record = { id, thread, canonicalId: id, similarity: null };
      records.push(record);
      canonicals.push({ id, anchor, body });
      continue;
    }

    let match = null;
    let matchSimilarity = 0;
    for (const canonical of canonicals) {
      if (!anchorsOverlap(anchor, canonical.anchor)) continue;
      const similarity = fingerprintSimilarity(body, canonical.body, shingleSize);
      if (similarity >= threshold && similarity > matchSimilarity) {
        match = canonical;
        matchSimilarity = similarity;
      }
    }

    if (match) {
      records.push({ id, thread, canonicalId: match.id, similarity: matchSimilarity });
    } else {
      records.push({ id, thread, canonicalId: id, similarity: null });
      canonicals.push({ id, anchor, body });
    }
  }

  const canonicalIds = new Set(canonicals.map((c) => c.id));
  const duplicateCount = records.filter((r) => r.canonicalId !== r.id).length;
  return { records, canonicalIds, duplicateCount };
}

function isThreadResolved(thread) {
  return thread?.isResolved === true;
}

/**
 * Effective guard obligations after dedup. Each canonical (or standalone /
 * detached / CodeQL) thread is counted at most once; a duplicate folds into its
 * canonical and inherits its resolution.
 *
 * - applyInheritance=false (shadow mode): the unresolved COUNT is byte-identical
 *   to today's raw unresolved count, but ledger/measurement data is still
 *   produced so a false-merge would be visible before enforcement flips.
 * - applyInheritance=true (enforce): a duplicate whose canonical is resolved no
 *   longer contributes an obligation; resolving the canonical auto-satisfies it.
 *
 * `wouldBeLostUniqueFindings` reports duplicates whose canonical is UNRESOLVED —
 * i.e. findings enforcement would still surface, proving no distinct finding is
 * hidden by the merge.
 */
export function computeGuardObligations(threads, config = REVIEW_DEDUP_CONFIG, options = {}) {
  const applyInheritance = options.applyInheritance === true;
  const { records, duplicateCount } = dedupeThreads(threads, config);
  const byId = new Map(records.map((r) => [r.id, r]));

  const canonicalResolved = new Map();
  for (const record of records) {
    if (record.canonicalId === record.id) {
      canonicalResolved.set(record.id, isThreadResolved(record.thread));
    }
  }

  const rawUnresolved = [];
  const effectiveUnresolved = [];
  const wouldBeLostUniqueFindings = [];

  for (const record of records) {
    const { thread } = record;
    if (isNonDedupThread(thread)) continue; // Guard already excludes CodeQL.
    const selfResolved = isThreadResolved(thread);
    if (!selfResolved) rawUnresolved.push(thread);

    const isDuplicate = record.canonicalId !== record.id;
    if (!isDuplicate) {
      if (!selfResolved) effectiveUnresolved.push(thread);
      continue;
    }

    const canonicalIsResolved = canonicalResolved.get(record.canonicalId) === true;
    if (!selfResolved && !canonicalIsResolved) {
      // Canonical still open: the finding is NOT hidden — it surfaces via the
      // canonical, so nothing is lost, and we do not double-count the duplicate.
      wouldBeLostUniqueFindings.push({
        id: record.id,
        canonicalId: record.canonicalId,
        surfacedByCanonical: true,
      });
    }
    if (!applyInheritance && !selfResolved) {
      effectiveUnresolved.push(thread); // Shadow: preserve raw count.
    }
  }

  return {
    records,
    duplicateCount,
    rawUnresolvedCount: rawUnresolved.length,
    effectiveUnresolvedCount: effectiveUnresolved.length,
    effectiveUnresolved,
    wouldBeLostUniqueFindings,
  };
}

/**
 * Per-round ledger lines for the gate summary comment (measurement hook,
 * umbrella decision D). Reports threads filed, deduplicated, unique-by-reviewer,
 * and the canonical link each duplicate was merged into so a false merge is
 * visible and one `not-a-duplicate` reply reverses it.
 */
export function formatRoundLedger(threads, config = REVIEW_DEDUP_CONFIG) {
  const { records, duplicateCount } = dedupeThreads(threads, config);
  const filed = records.length;
  const uniqueByReviewer = new Map();
  for (const record of records) {
    if (record.canonicalId !== record.id) continue;
    const login = firstAuthorLogin(record.thread) ?? "unknown";
    uniqueByReviewer.set(login, (uniqueByReviewer.get(login) ?? 0) + 1);
  }

  const canonicalUrl = (id) => {
    const record = records.find((r) => r.id === id);
    const comment = record?.thread?.comments?.nodes?.[0];
    return comment?.url ?? `thread ${id}`;
  };

  const dedupLines = records
    .filter((r) => r.canonicalId !== r.id)
    .map(
      (r) =>
        `- ${firstAuthorLogin(r.thread) ?? "unknown"} duplicate of ${canonicalUrl(
          r.canonicalId,
        )} (similarity ${r.similarity.toFixed(2)})`,
    );

  const uniqueSummary = [...uniqueByReviewer.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([login, count]) => `${login}: ${count}`)
    .join(", ");

  const header =
    `Review-thread dedup: ${filed} filed, ${duplicateCount} deduplicated` +
    (duplicateCount > 0 ? ` → ${duplicateCount} canonical link(s) below` : "") +
    `; unique-by-reviewer — ${uniqueSummary || "none"}.`;

  return duplicateCount > 0 ? [header, ...dedupLines].join("\n") : header;
}
